### ISSUE TITLE
Fix metadata display and navigation functions on blackboard nodes

### ISSUE THREAD

**Issue by mbrush** [NCATS-Tangerine/beacon-aggregator#19]
At present, tk.bio  behavior when clicking on a concept node in the blackboard is variable.  For some concepts (mostly Wikidata ones) a nice table showing concept metadata appears, and the user is given the option to  show relations' for that concept in the statement table.  But for many concepts (e.g. those from Biolink), no metadata is returned, and the 'show relations' button does not work. This is a significant barrier to navigation of the data in the way we would like to support.

Image below shows dialog box returned after clicking a concept node from Biolink - no metadata returned as for most Wikidata nodes, and also the 'show relations' box is inactive/greyed out.
  
![image](https://user-images.githubusercontent.com/5184212/30606948-4007f370-9d28-11e7-8eb3-c396cf7766c3.png)

**Comment by RichardBruskiewich** [comment]
Thanks Matt, this issue actually belongs on the TKBio repo, not in the beacon-aggregator, which is just the REST API. I'm tempted to somehow transfer it over (if there is a simple way of doing this) although for the time being, it is simply good to have it recorded here.

**Comment by mbrush** [comment]
Hi Richard - sure.  I can create a copy of this as a new issue there, and close this one.  Please let me know if there are other issues I created in this repo that belong elsewhere - I suspect most if not all should also be moved to the tk.bio tracker as well?  Happy  to do so.

**Comment by mbrush** [comment]
moved issue to tk.bio repo
