### ISSUE TITLE
beacon-aggregator README and API specification needs a bit of elaboration

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATS-Tangerine/beacon-aggregator#8]
1) need to properly document the functionality of the beacon-aggregator
2) need to provide examples queries in the OpenAPI spec for the beacon-aggregator

**Comment by lhannest** [comment]
I put in a pull request for more documentation of how it loads beacons: https://github.com/NCATS-Tangerine/beacon-aggregator/pull/10

Could you explain in more detail what you want documented, though?

**Comment by RichardBruskiewich** [comment]
Enhanced [beacon aggregator README](https://github.com/NCATS-Tangerine/beacon-aggregator/blob/develop/README.md)
